version: '3.8'
services:

  hydra-migrate:
    image: oryd/hydra:v1.10.2
    environment:
      - DSN=postgres://hydra:secret@postgres-dev:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4

  hydra:
    image: oryd/hydra:v1.10.2
    environment:
      - DSN=postgres://hydra:secret@postgres-dev:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4

  postgres-dev:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hydra
    networks:
      - intranet

networks:
  intranet:
